# Generated by Django 6.0 on 2026-03-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('hobbies', models.TextField()),
                ('skills', models.TextField()),
                ('address', models.TextField()),
                ('profile_photo', models.ImageField(upload_to='profile_photos/')),
            ],
        ),
    ]
