# Generated by Django 6.0 on 2026-02-18 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerdetails',
            old_name='empaddress',
            new_name='empemail',
        ),
    ]
