# Generated by Django 6.0 on 2026-02-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0002_rename_empaddress_employerdetails_empemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerdetails',
            name='empemail',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='employerdetails',
            name='empid',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employerdetails',
            name='emplocation',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='employerdetails',
            name='empname',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='employerdetails',
            name='empphone',
            field=models.CharField(max_length=120),
        ),
    ]
